# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: event_command_development
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

test:
  <<: *default
  database: event_command_test
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

production:
  primary:
    <<: *default
    database: event_command_production
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  cache:
    <<: *default
    database: event_command_production_cache
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: event_command_production_queue
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: event_command_production_cable
    username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
    host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
    migrations_paths: db/cable_migrate
