# Solid Queue configuration for Rails 8
# Jobs can run in the same process as your web server

default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 2
      processes: 1  # Same process as web server

development:
  <<: *default

test:
  <<: *default

production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    # High priority jobs (same process for immediate execution)
    - queues: "critical,default"
      threads: 3
      processes: 1
    # Low priority jobs (can be separate process if needed)
    - queues: "low_priority,mailers"
      threads: 2
      processes: 1